### PR TITLE
feat(all): add capability to disable securityContext

### PR DESCRIPTION
**Pull request by tduverge**
Hello,

In our deployments, we would like to be able to disable securityContext definitions.

Would it be possible to add this option?

### CODE REVIEW

**Comment by headlessme** [comment]
Could you please provide some more information on why it's important for you to run without the security context?

**Comment by tduverge** [comment]
On our k8s cluster, the user running the containers is automatically configured by k8s, different for each namespace and is not predictable.

We don't want to force security on our containers but only inherit the rules created by our k8s administrator.

**Comment by headlessme** [comment]
@tduverge thanks for the feedback here, we've discussed this internally and are planning to add a top level `containerSecurityContext` to the helm config rather than for each individual container. This should mean as we add new containers in the future, the `enabled` setting will be respected for the additions without requiring any further changes in your deployment.

The setting should be available in the next release. I don't have a firm timeline, likely within the next week or so. Please let us know if you have any further feedback!

**Comment by headlessme** [comment]
This is available in the latest release:

https://github.com/cobrowseio/cobrowse-enterprise-helm/blob/575a7fdb9d7623aeb39cbb3e79ed4106c1b26888/values.yaml#L107-L108

**Comment by tduverge** [comment]
@headlessme Thanks for the action Andy.
I set the containerSecurityContext for each container because this is the way to do it on redis chart that you recommend in your [documentation](https://docs.cobrowse.io/enterprise-self-hosting/helm#dependencies). But for us the syntax doesn't matter, we just need to be able to disable it.
Thanks again, we will try it next week.

**Pull request closed without merging**
